import Footer from '../components/Footer';
import Nav from '../components/Nav';
import './globals.css'

// Metadata
export const metadata = {
  title: 'Ramone Personal Chef',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-screen-xl mx-auto bg-slate-100 font-serif">
        
        <div className='flex flex-col min-h-screen bg-white'>
          <Nav />
          {children}
          <Footer />
        </div>
        
      </body>
    </html>
  );
}