import Footer from '../components/Footer';
import Nav from '../components/Nav';
import './globals.css'

// Metadata
export const metadata = {
  title: 'Ramone Personal Chef',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen mx-2">
        
        <Nav />
        {children}
        <Footer />
        
      </body>
    </html>
  );
}